#-------------------------------------------------------------------------------#
# Frontend for UFPS Training Center                                             #
# Based on Alpine linux                                                         #
#-------------------------------------------------------------------------------#

# Pull base image
FROM nginx:alpine

# Container Basic Info 
MAINTAINER GERSON LAZARO
MAINTAINER MELISSA DELGADO

# Copy files to container
COPY . /usr/share/nginx/html