version: '3'
services:
  frontend:
    build: "frontend"
    image: "frontend"
    container_name: "training-center-frontend"
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  backend:
    build: "backend"
    image: "backend"
    container_name: "training-center-backend"
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_URL=${DATABASE_URL}"
      - "SECRET_TOKEN=${SECRET_TOKEN}"
    volumes:
      - "${FILES}:/usr/src/app/files"
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      - db
      - cpp
      - java
      - python
    
  db:
    image: "mariadb:10.2"
    restart: "always"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=development"
    container_name: "mariaDB"
    ports:
      - "${DATABASE_PORT}:3306"

  cpp:
    build: "grading/cpp"
    image: "cpp_image"
    container_name: "cppSandbox"
    volumes:
      - "${FILES}:/files"
    tty: true

  java:
    build: "grading/java"
    image: "java_image"
    container_name: "javaSandbox"
    volumes:
      - "${FILES}:/files"
    tty: true

  python:
    build: "grading/python"
    image: "python_image"
    container_name: "pythonSandbox"
    volumes:
      - "${FILES}:/files"
    tty: true

